### ISSUE TITLE
有关技术栈怎样算学会了的疑问

### ISSUE THREAD

**Issue by yenaibangbing** [forrestbao/Run#5]
教授你好我是中国一名大一cs的学生，看到这个招聘有点心动，现在打算一年内达到toefl95的同时学习一点有关web development或者是nlp相关的技术栈，但对于前者我想知道一下达到什么样的程度算是符合要求的，希望您可以给我一点提示或者是指导，谢谢.

**Comment by Himself65** [comment]
精通JavaScript（精通指的是了解JavaScript的历史遗留问题，知道如何从v8解释器引擎的角度分析一些js代码），熟悉TypeScript
基础的技术栈：node.js, 三大web框架之一（vue、react、angular）
前端生态链：测试框架（如Jest），Lint工具（ESLint）、workspaces（例如yarn workspace）、构建工具（webpack、rollup、glup），以及其他微小的工具（husky、prettier）……
前端比较前沿的东西：nextjs（serverless + ssr）、wasm（如deno.ts、swc）……

这里随便想到什么就写出来，不完全对
